### ISSUE TITLE
不支持可重入和锁续期

### ISSUE THREAD

**Issue by hellomdk** [cheerego/go-redisson#3]
老哥，你这个不支持可重入和锁续期吧，没看到可重入相关的lua脚本

**Comment by cheerego** [comment]
可重入  https://github.com/cheerego/go-redisson/blob/3a07f85ab4535e4849ffcba561db16c41fecdd16/rlock.go#L198
续期 https://github.com/cheerego/go-redisson/blob/3a07f85ab4535e4849ffcba561db16c41fecdd16/rlock.go#L259

**Comment by cheerego** [comment]
是支持的。

Mutex 是不可重入锁类似于 sync.Mutex
Rlock 是可重入锁，通过 goroutineId 作为可重入标识符

他们两个都是支持续期的

**Comment by cheerego** [comment]
如果不需要可重入特性的话，直接用 Mutex。
如果需要可重入特性的话，就用 RLock。
